[workspace]
name = "scipystack"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[dependencies]
ipython = ">=9.4.0,<10"
numpy = { path = "numpy" }
pywavelets = { path = "pywt" }
meson = { path = "meson" }
scipy = { path = "scipy" }
matplotlib = ">=3.10.5,<4"
# TODO

[tasks]
start = "python scripts/interp.py"
