[workspace]
name = "scipystack"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]
preview = ["pixi-build"]

[dependencies]
# TODO

[tasks]
start = "python scripts/interp.py"
