[workspace]
name = "cpython"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[package]
name = "python"
version = "3.13.7"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[dependencies]
python = { path = "." }
