[workspace]
name = "meson"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]
preview = ["pixi-build"]


[package]
name = { workspace = true }
version = "1.9.0.rc2"

[package.build]
backend = { name = "pixi-build-python", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",

]
source.path = "meson"

[package.host-dependencies]
setuptools = ">=42"
uv = "*"


[dependencies]
meson = { path = "." }

[tasks]
help = { cmd = "meson --help" }
