[workspace]
name = "meson"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]
preview = ["pixi-build"]


[package]
name = { workspace = true }
version = "1.9.0.rc2"

[package.build]
backend.name = "pixi-build-python"
backend.version = "*"
source.path = "meson"

[package.host-dependencies]
setuptools = ">=42"
python = "*"
uv = "*"


[dependencies]
meson = { path = "." }

[tasks]
help = { cmd = "meson --help" }
