context:
  version: 3.13.7

package:
  name: python
  version: ${{ version }}

source:
  path: ../cpython

build:
  number: 0
  files:
    exclude:
      - "*.o"
  script:
    file: build.sh
    env:
      MINOR_VERSION: "3.13"
      PYTHON_ASAN: "1"

requirements:
  build:
    - ${{ compiler('c') }}
    # - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - make
    - libtool
    - pkg-config
    # configure script looks for llvm-ar for lto
    - clang-18
    - llvm-tools-18

  host:
    - bzip2
    - sqlite
    - liblzma-devel
    - zlib
    - openssl
    - readline
    - tk
    # These two are just to get the headers needed for tk.h, but is unused
    - xorg-libx11
    - xorg-xorgproto
    - ncurses
    - libffi
    - libmpdec-devel
    - expat

about:
  homepage: https://www.python.org/
  license: Python-2.0
  license_file: LICENSE
  summary: General purpose programming language
  description: |
    Python is a widely used high-level, general-purpose, interpreted, dynamic
    programming language. Its design philosophy emphasizes code readability
    with the use of significant indentation.
  documentation: https://www.python.org/doc/versions/
  repository: https://docs.python.org/devguide/
